### ISSUE TITLE
Exception if index does not exists.

### ISSUE THREAD

**Issue by stian-overasen** [DekodeInteraktiv/project-base#169]
https://github.com/DekodeInteraktiv/project-base/blob/0b814bb1842dfd236ce300125278e9044b9ac0ea/config/application.php#L23

This line should use a null coalescing operator:
`return $_ENV[ $key ] ?? ''; // phpcs:ignore`

_The Elvis operator (`?:`) does not do a null check in array._

**Comment by Clorith** [comment]
Resolved in f90d254
