### ISSUE TITLE
Can we link to Dekode coding starndards

### ISSUE THREAD

**Issue by henningdekode** [DekodeInteraktiv/project-base#283]
In the pull request template https://github.com/DekodeInteraktiv/project-base/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Can we link to the Dekode Coding standards repo?
https://github.com/DekodeInteraktiv/coding-standards

**Comment by walbo** [comment]
Not sure we should add it because the text will be less readable.

When creating a new PR the `write` mode will show something like this:
```
- [ ] My code follows the [Dekode coding standards](https://github.com/DekodeInteraktiv/coding-standards)
```

compared to how it is today

```
- [ ] My code follows the Dekode coding standards
```

**Comment by Clorith** [comment]
I tend to agree with @walbo here, the coding standards are also built into the local tooling, so this should not come as a surprise to anyone, alterantively it could be mentioned in the project readme as an aside?
