### ISSUE TITLE
The html/body/entry-content should never exceed 100vw

### ISSUE THREAD

**Issue by Sisanu** [DekodeInteraktiv/project-base#354]
The pages should never have a horizontal scroll, there is no actual scenario in which that is required, and we could fix this in the theme.

See an example of a simple wide element breaking the page.
https://capture.dropbox.com/ugI3mxMwhsV6fJ2P

**Comment by zpaceinvader** [comment]
what are the steps to replicating this?

**Comment by Sisanu** [comment]
Just embed in the page a div with a very big width (use HTML in the editor for example). But it can be replicable in any context where the menu is wide and it slides into view, or any carousel/slider feature (that arranges all elements in a row and computes the width like the sum of elements and just transitions the wrapper element to the left or right)

**Comment by olethomas** [comment]
Closing this as wontfix. This should be solved per project.
