### ISSUE TITLE
PHP linting bug when using params by reference in functions

### ISSUE THREAD

**Issue by peroks** [DekodeInteraktiv/project-base#394]
When passing variables by reference to a function, the php linter claims that the argument type is missing, even if it's not.

`protected function prepare_block_reference( array &$block, int $site_id, string $attribute ): int {`

```
FILE: .../mollie/app/packages/plugins/mollie-blueprint/inc/class-sync.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 544 | WARNING | Argument type is missing
     |         | (NeutronStandard.Functions.TypeHint.NoArgumentType)
----------------------------------------------------------------------
```

**Comment by olethomas** [comment]
We should remove Neutron from our coding standards. The neutron standard from Automattic is not actively maintained anymore.

**Comment by olethomas** [comment]
Started a draft to update our coding standards here: https://github.com/DekodeInteraktiv/coding-standards/pull/26

Needs optimizing and testing before we can merge. Anyone?

**Comment by stian-overasen** [comment]
Fixed with https://github.com/DekodeInteraktiv/coding-standards/releases/tag/5.0.0
